/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1d8bd44aa22a0f5f311914c781475e8d)
interface __BaseEnv_Env {
	EVENTS: KVNamespace;
	DB: D1Database;
	RL_IP: RateLimit;
	RL_ADMIN: RateLimit;
	RL_USER: RateLimit;
	RL_QUOTE: RateLimit;
	RL_WRITE: RateLimit;
	AI: Ai;
	LIVE: "false";
	PAYOUT_PROVIDER: "sandbox";
	PRIVY_API_URL: "https://api.privy.io";
	SUMSUB_LEVEL: "id-and-liveness";
	SOLANA_RPC_URL: "";
	CLEF_ENABLED: "true";
	PRIVY_WEBHOOK_SIGNING_SECRET: string;
	PRIVY_VERIFICATION_KEY: string;
	PRIVY_APP_ID: string;
	PRIVY_APP_SECRET: string;
	ADMIN_API_KEY: string;
	PAYOUT_WEBHOOK_SECRET: string;
	PRIVY_DEPOSIT_POLICY_EVM: string;
	PRIVY_DEPOSIT_POLICY_SOL: string;
	TREASURY_EVM: string;
	TREASURY_SOL: string;
	ALERT_WEBHOOK_URL: string;
	PRIVY_DENY_SET_EVM: string;
	PRIVY_DENY_SET_SOL: string;
	PAWAPAY_BASE_URL: string;
	PAWAPAY_API_TOKEN: string;
	PRIVY_SIGNER_ID: string;
	PRIVY_SIGNER_PRIVATE_KEY: string;
	PRIVY_SWAP_POLICY_EVM: string;
	PRIVY_SWAP_POLICY_SOL: string;
	SUMSUB_SECRET: string;
	SUMSUB_TOKEN: string;
	SUMSUB_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LIVE" | "PAYOUT_PROVIDER" | "PRIVY_API_URL" | "SUMSUB_LEVEL" | "SOLANA_RPC_URL" | "CLEF_ENABLED" | "PRIVY_WEBHOOK_SIGNING_SECRET" | "PRIVY_VERIFICATION_KEY" | "PRIVY_APP_ID" | "PRIVY_APP_SECRET" | "ADMIN_API_KEY" | "PAYOUT_WEBHOOK_SECRET" | "PRIVY_DEPOSIT_POLICY_EVM" | "PRIVY_DEPOSIT_POLICY_SOL" | "TREASURY_EVM" | "TREASURY_SOL" | "ALERT_WEBHOOK_URL" | "PRIVY_DENY_SET_EVM" | "PRIVY_DENY_SET_SOL" | "PAWAPAY_BASE_URL" | "PAWAPAY_API_TOKEN" | "PRIVY_SIGNER_ID" | "PRIVY_SIGNER_PRIVATE_KEY" | "PRIVY_SWAP_POLICY_EVM" | "PRIVY_SWAP_POLICY_SOL" | "SUMSUB_SECRET" | "SUMSUB_TOKEN" | "SUMSUB_WEBHOOK_SECRET">> {}
}
