/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6fa0ecceef26161ed720d1a506c17188)
interface __BaseEnv_Env {
	EVENTS: KVNamespace;
	DB: D1Database;
	LIVE: "false";
	PAYOUT_PROVIDER: "sandbox";
	SOLANA_RPC_URL: "";
	PRIVY_WEBHOOK_SIGNING_SECRET: string;
	PRIVY_VERIFICATION_KEY: string;
	PRIVY_APP_ID: string;
	PRIVY_APP_SECRET: string;
	ADMIN_API_KEY: string;
	PAYOUT_WEBHOOK_SECRET: string;
	PRIVY_DEPOSIT_POLICY_EVM: string;
	PRIVY_DEPOSIT_POLICY_SOL: string;
	TREASURY_EVM: string;
	TREASURY_SOL: string;
	ALERT_WEBHOOK_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LIVE" | "PAYOUT_PROVIDER" | "SOLANA_RPC_URL" | "PRIVY_WEBHOOK_SIGNING_SECRET" | "PRIVY_VERIFICATION_KEY" | "PRIVY_APP_ID" | "PRIVY_APP_SECRET" | "ADMIN_API_KEY" | "PAYOUT_WEBHOOK_SECRET" | "PRIVY_DEPOSIT_POLICY_EVM" | "PRIVY_DEPOSIT_POLICY_SOL" | "TREASURY_EVM" | "TREASURY_SOL" | "ALERT_WEBHOOK_URL">> {}
}
